group:
  - files:
    - source: .gitsecret/
      dest: .gitsecret/
    - source: .balena/secrets/
      dest: .balena/secrets/
    repos: |
      product-os/jellyfish-plugin-typeform
      product-os/jellyfish-plugin-balena-api
      product-os/jellyfish-plugin-outreach
      product-os/jellyfish-plugin-flowdock
      product-os/jellyfish-plugin-github
      product-os/jellyfish-plugin-front
      product-os/jellyfish-plugin-discourse
      product-os/jellyfish-action-library
      product-os/jellyfish
