group:
  - files:
    - source: .gitsecret/
      dest: .gitsecret/
    - source: .balena/secrets/
      dest: .balena/secrets/
    repos: |
      product-os/jellyfish-plugin-typeform
      product-os/jellyfish-plugin-balena-api
