# This file is auto-synced from product-os/jellyfish-config/sync/.resinci-no-docker.yml
# and should only be edited there!

npm:
  platforms:
    - name: linux
      os: alpine
      architecture: x86_64
      node_versions:
        - "14"
        - "16"
