# This workflow synchronizes files from this repo into other repos
# if they have changed. The 'magic' happens thanks to this action:
# https://github.com/marketplace/actions/repo-file-sync-action

name: Sync Files

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1.13.3
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          COMMIT_BODY: "Change-type: patch"
          COMMIT_EACH_FILE: false
